[package]
name = "twist-rs"
version = "0.1.0"
authors = ["PotHix <pothix@pothix.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
reqwest = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
