[package]
name = "twist-rs"
version = "0.1.0"
authors = ["PotHix <pothix@pothix.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.3"
