/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Twist */

#ifndef _Included_Twist
#define _Included_Twist
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Twist
 * Method:    search
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Twist_search
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
